### ISSUE TITLE
Gallery Images

### ISSUE THREAD

**Issue by shaayaanjameel** [shaayaanjameel/dsn1676-term-project#1]
@thomasjbradley

My gallery images for graphic design section won't line up when it gets to m/l screen size. I have a grid on it and gave it a display inline-block and it's still not working.

**Comment by thomasjbradley** [comment]
Is that these image?
https://github.com/shaayaanjameel/dsn1676-term-project/blob/gh-pages/index.html#L49-L52

**Comment by shaayaanjameel** [comment]
Yes it is.

@thomasjbradley

**Comment by thomasjbradley** [comment]
I think it's because they have a really big margin on the left.
